application: bolognium-source
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- datastore_admin: on

handlers:
- url: /js/(.*\.js)
  static_files: static/js/\1
  upload: static/js/(.*)

- url: /html/(.*\.html)
  static_files: static/html/\1
  upload: static/html/(.*)

- url: /img/(.*\.(gif|png|jpg|jpeg|ico))
  static_files: static/img/\1
  upload: static/img/(.*\.(gif|png|jpg|jpeg|ico))

- url: /css/(.*\.css)
  static_files: static/css/\1
  upload: static/css/(.*)

- url: /favicon.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico

- url: /admin.*
  script: main.application
  login: admin

- url: /.*
  script: main.application

libraries:
- name: PIL
  version: latest
- name: lxml
  version: latest
- name: webapp2
  version: latest
- name: webob
  version: latest
- name: jinja2
  version: latest
- name: markupsafe
  version: latest

inbound_services:
- warmup
